config/routes.rb
Rails.application.routes.draw do
  get "offers/index"
  root "offers#index"
  resources :offers
  resources :categories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :offers

    def to_s
        "#{name}"
    end
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # before_action :authenticate_user!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: %i[ show edit update destroy ]

  # GET /offers or /offers.json
  def index
    @offers = Offer.all
  end

  # GET /offers/1 or /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers or /offers.json
  def create
    @offer = Offer.new(offer_params)
    respond_to do |format|
      if @offer.save
        format.html { redirect_to @offer, notice: "Offer was successfully created." }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1 or /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to @offer, notice: "Offer was successfully updated." }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1 or /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url, notice: "Offer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_offer
    @offer = Offer.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def offer_params
    params.require(:offer).permit(:user, :title, :description, :price, :adress, :phone, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<div class=categorie>
  <h2>Categories</h2>
</div>

<table class="table table-striped">
  <thead>
    <tr>
    
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category, class: 'btn btn edit'%></td>
        <td><%= link_to 'Edit', edit_category_path(category), class: 'btn btn edit' %></td>
        <td><%= link_to 'Destroy', category,class: 'btn btn edit', method: :delete, data: { confirm: "C'est votre dernier mot Jean-Pierre ?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="d-grid gap-2 col-4 mx-auto" style="margin-top: 1.5rem;margin-bottom: 6rem">
  <%= link_to 'New Category', new_category_path, class: 'btn btn-back'%>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
  
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet"> 
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet"> 
    
    <title>RefWeb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

  <body>

  <nav class="navbar navbar-dark bg-dark" style="margin-bottom:4rem">
        <div class= "Offer">
          <h1><%= link_to "Les Offres", offers_path(@offers) %></h1>
        </div>

        <div class= "category"> 
          <%= link_to "Catégories", categories_path(@categories) %></div>
        </div>
  </nav>

    <main class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/offers/_form.html.erb
<%= simple_form_for offer do |f| %>
<div class="forms"> 
    <%= f.input :title%>
    <%= f.input :user %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :adress %>
    <%= f.input :phone %>
    <%= f.association :category %>
  </div>

  
<div class="d-grid gap-2 col-6 mx-auto" style="margin-top: 4rem">
    <%= f.button :submit %>
</div>

<% end %>

app/views/offers/edit.html.erb
<h1>Editing Offer</h1>

<%= render 'form', offer: @offer %>

<%= link_to 'Show', @offer %> |
<%= link_to 'Back', offers_path %>

app/views/offers/index.html.erb
<p id="notice"><%= notice %></p>

<div class="d-grid gap-2 col-6 mx-auto" style="margin-top: 6rem;">
    <%= link_to 'Créer une Offre !', new_offer_path, class: 'btn btn' %>
</div>

<figure class="text-center">
  <blockquote class="blockquote" >
    <p>Dépose ta recherche ou ton offre d'emploie pour et rejoins la webteam !</p>
  </blockquote>
</figure>

<div class="d-flex justify-content-start flex-wrap" style="gap: 3rem">
  <% @offers.each do |offer| %>
    <div><a class="offer-card-link" href="<%= offer_path(offer.id) %>">
      <div class="card mb-3" style="max-width: 20rem;">
        <div class="card-header"><%= offer.user %></div>
        <div class="card-body">
          <h5 class="card-title"><%= offer.title %></h5>
          <p class="card-text"><%= offer.description %></p>
          <p class="card-text"><small class="text-muted"><%= offer.price %>€</small></p>
        </div>
    </div>
    </a></div>
  <% end %>
</div>


<br>

app/views/offers/new.html.erb
<div class="new-offer"><h1>Créer ton offre !</h1></div>


<%= render 'form', offer: @offer %>

<div class="d-grid gap-2 col-4 mx-auto" style="margin-top: 1.5rem;margin-bottom: 6rem">
    <%= link_to 'Back', offers_path, class: 'btn btn-back'%>
    </div>

app/views/offers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @offer.user %>
</p>

<p>
  <strong>Title:</strong>
  <%= @offer.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @offer.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @offer.price %>
</p>

<p>
  <strong>Adress:</strong>
  <%= @offer.adress %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @offer.phone %>
</p>

<p>
  <strong>Category:</strong>
  <%= @offer.category_id %>
</p>

<%= link_to 'Edit', edit_offer_path(@offer) %> |
<%= link_to 'Back', offers_path %>
<%= link_to 'Destroy', @offer, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>